language: node_js
sudo: required
services:
- docker
env:
  global:
  - TF_VAR_gcloud_creds=${TRAVIS_BUILD_DIR}/test/usermirror-staging.json
  - TF_VAR_kubeconfig=test-kubeconfig

cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'

before_install:
- make setup-env
- openssl aes-256-cbc -K ${encrypted_bd41513aa00e_key} -iv ${encrypted_bd41513aa00e_iv} -in ./test/usermirror-staging.json.encrypted -out ${TF_VAR_gcloud_creds} -d

install:
- make build

script:
- make check
- gcloud auth activate-service-account --key-file=${TF_VAR_gcloud_creds}
- mkdir ~/.docker && gcloud beta auth configure-docker --quiet
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- |
    if [ ! -z ${TRAVIS_TAG} ]; then
        TAG=${TRAVIS_TAG} make release
    else
        make push
    fi